"""update tables

Revision ID: b095120a6c8a
Revises: 1b7a2afefa01
Create Date: 2025-05-28 16:25:38.467945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b095120a6c8a'
down_revision: Union[str, None] = '1b7a2afefa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_profile_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_profile_id_fkey'), 'users', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###
